spring:
 datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost/springboot?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Africa/Lagos
  username: root
  password:
 jpa:
  hibernate.ddl-auto: update
  generate-ddl: true
  show-sql: true